<?php
define ('MAX_DISPLAY_NEW_PRODUCTS', 4);
define ('SMALL_IMAGE_WIDTH', 88);
define ('SMALL_IMAGE_HEIGHT', 169);
define ('MAX_DISPLAY_CATEGORIES_PER_ROW', 3);
define ('SUBCATEGORY_IMAGE_WIDTH', 100);
define ('SUBCATEGORY_IMAGE_HEIGHT', 62);
define ('HEADING_IMAGE_WIDTH', 0);
define ('HEADING_IMAGE_HEIGHT', 1);
?>
